# Generated by Django 4.2.2 on 2023-06-07 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SI_NO', models.IntegerField()),
                ('Item', models.CharField(max_length=250)),
                ('Desc', models.CharField(max_length=250)),
            ],
        ),
    ]
