# Generated by Django 4.2.2 on 2023-06-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='Desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='Item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='SI_NO',
            new_name='si',
        ),
    ]
